title: Solid Late
description: Documentation of the Lighting Reindeer FabLab project
author: Solid Late
logo: /static/img/avatar.png
github: https://github.com/solid-late
about: Reindeer LED FabLab Project

baseurl: ""
url: ""

allowsearch: true

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
